Feature/scrum 24
Pablo2904/rick-morty-app pull request #10
Opened 2024-12-16 11:28 UTC by Michaljarek

2024-12-16 14:51 UTC, AlicjaSzot commented on rick-morty-app-client/src/components/atoms/Avatar/Avatar.module.scss
Remove "../../../" from line 1 and 2

2024-12-16 14:56 UTC, AlicjaSzot commented on rick-morty-app-client/src/components/molecules/StatusBadge/StatusBadge.module.scss
> +@use "../../../styles/variables" as *;
It should be:
 "@use "styles/mixins" as *;
 @use "styles/variables" as *;

2024-12-16 15:03 UTC, AlicjaSzot commented on rick-morty-app-client/src/components/molecules/StatusBadge/StatusBadge.tsx
In folder "config" > folder "webpack" find "webpack.config.js" > search "alias" (313 line) and in this part add path for your types folder. it should be like this: 
"@types": path.resolve(__dirname, "src/types"),". 
And Next in your StatusBadge.tsx file change path for import CharacterStatus to "import { CharacterStatus } from "types/CharactersTypes";"

Reszta nie wiem co sie dzieje, ale jak działa to ok.

2024-12-18 13:49 UTC, Michaljarek commented on rick-morty-app-client/src/components/molecules/StatusBadge/StatusBadge.tsx
Działa

2024-12-18 14:12 UTC, Pablo2904 requested changes

2024-12-18 14:12 UTC, Pablo2904 commented on rick-morty-app-client/src/components/molecules/StatusBadge/StatusBadge.tsx
> +import { CharacterStatus } from "../../../types/CharactersTypes";
remove ../../../

2024-12-19 13:35 UTC, Pablo2904 approved these changes

2024-12-19 13:38 UTC, merged