feature/SCRUM-17 Implement Axios for REST Communication
Pablo2904/rick-morty-app pull request #13
Opened 2024-12-18 12:14 UTC by AlicjaSzot

Implement Axios for REST Communication

2024-12-18 14:03 UTC, Pablo2904 requested changes

2024-12-18 14:03 UTC, Pablo2904 commented on rick-morty-app-client/package.json
> +    "@types/axios": "^0.14.4",
axios chyba ma juz typy zaimplementowane w ramach biblioteki, napeno to jest potrzebne>?

2024-12-18 14:03 UTC, Pablo2904 commented on rick-morty-app-client/src/api/axiosInstance.tsx
> +axios.interceptors.request.use(
te interceptors chyba nie ebda ptorzebne

2024-12-18 14:03 UTC, Pablo2904 commented on rick-morty-app-client/src/api/characterApi.tsx
> +export const fetchCharacters = async () => {
getCharacters

2024-12-18 14:03 UTC, Pablo2904 commented on rick-morty-app-client/src/api/characterApi.tsx
> +export const fetchCharacters = async () => {
Ta funckja powinna zwracac dane Typu Characters[]

2024-12-18 17:42 UTC, AlicjaSzot commented on rick-morty-app-client/package.json
> +    "@types/axios": "^0.14.4",
wyświetlało mi errory i jak zainstalowałam to to już było git, a więc jest niezbędne

2024-12-18 17:43 UTC, AlicjaSzot commented on rick-morty-app-client/src/api/characterApi.tsx
> +export const fetchCharacters = async () => {
poprawione

2024-12-18 18:12 UTC, AlicjaSzot commented on rick-morty-app-client/src/api/axiosInstance.tsx
> +axios.interceptors.request.use(
poprawione - interceptors usuniete

2024-12-18 18:12 UTC, AlicjaSzot commented on rick-morty-app-client/src/api/characterApi.tsx
> +export const fetchCharacters = async () => {
już zwraca - poprawione

2024-12-18 20:55 UTC, Pablo2904 approved these changes

2024-12-19 14:27 UTC, Michaljarek approved these changes

2024-12-19 16:18 UTC, merged