feature/SCRUM-16 Implement Toast Messaging
Pablo2904/rick-morty-app pull request #15
Opened 2024-12-19 19:34 UTC by AlicjaSzot

Created Context for Toast Notifications

W zadaniu trzeba było stworzyć przykładowy toast, więc zrobiłam go w HomePage. Nie wiem, czy mam to zostawić czy usunąć, więc zakomentowałam póki co.

2024-12-19 23:58 UTC, Pablo2904 requested changes
nie wiem o chuj tu chodzi, chce po prostu gdzies w kodzie sobie wywołać
toast({type: 'success', message: 'Jakis message'})
bez uzywania predefined itp
 a tak wgl message dla kazdego toasty powinnien byc tluamczeniem

2024-12-19 23:58 UTC, Pablo2904 commented on rick-morty-app-client/src/context/ToastContext/ToastContext.tsx
> +    switch (type) {
zamiast switch, porostu if if if if

2024-12-19 23:58 UTC, Pablo2904 commented on rick-morty-app-client/src/context/ToastContext/ToastContext.tsx
> +const predefinedMessages: ToastMessages = {
po co jakies predefiniowane message?

2025-01-02 22:44 UTC, AlicjaSzot commented
Zrobiłąm przykłądowy kompoennt,w  któym wywoływane sa te toasty za pomoca klikniecia w odpowiedni button. Nie wiem czy to ok, czy może lepiej usunąć ten komponent i po prostu w jakimś miejscu w kodzie np. w HomePage 
1) stworzyć sobie funkcje np. coś takiego:
const handleSuccessToast = () => {
    toast({ type: "success", message: "Your changes were saved successfully." });
  }; 
  + to samo dla type info i error
  2) dodać button i do niego onClick=handleSuccessToast, żeby na klikniecie się wywoływało.
  ?

2025-01-09 12:20 UTC, Michaljarek approved these changes

2025-01-09 12:22 UTC, Michaljarek approved these changes

2025-01-11 14:15 UTC, Pablo2904 approved these changes

2025-02-16 15:33 UTC, merged